### ISSUE TITLE
Problems executing some plugins

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#10]
I struggle to run some plugins after installation.

Screewmaker fights with pluginloader for screen space and does not seam to be able to make screews.

workfeature does not start for me unless i move contents of Mod/plugins/WorkFeature/WorkFeature/ to Mod/plugins/WorkFeature

Joinfeatures is in Master now, when installed in current master this messes up Part module and crashes it if switched to part. Should be removed or handled somehow.

PCB does not install: references to fixed folder source:/home/thomas/tmp/PCB!

Symbollib 
Does not look ready for auto install and configure
Looks like it installs fine, but fails on run with:
fn="/usr/lib/freecad/Mod/plugins/FreeCAD-symbols/SymbolsLibrary.FCMacro";exec open(fn).read()
  File "<string>", line 140, in <module>
-->    File "<string>", line 92, in **init**
-->  NameError: global name 'QtSvg' is not defined

Animation does not install properly. Downloaded, extracted but not installed.

PartLibrary Does not look ready for auto install and configure

CircularText Macro points to PartLibrary when run
fn="/usr/lib/freecad/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()

Perfect function.
Cura Engine  Perfect install, Perfect run
ObjTree Perfect install, Perfect run
DrawingDim Perfect install, Perfect run
Exploded Animation Perfect install, Perfect run
Bolts Perfect install, Perfect run

TestPM
*****default Method FreeCAD-Dir=/usr/lib/freecad/! HOME-Dir=/home/kjetil/!  UserData-Dir=/home/kjetil/.FreeCAD/!

**Comment by microelly2** [comment]
**_\+ my comments -**_

I struggle to run some plugins after installation.

Screewmaker fights with pluginloader for screen space and does not seam to be able to make screews.
_**+
yes, i have a local copy that already works - needs communication
*_*-

workfeature does not start for me unless i move contents of Mod/plugins/WorkFeature/WorkFeature/ to Mod/plugins/WorkFeature
_**+
seams to be a bug again with the shutil.move
*_*-

Joinfeatures is in Master now, when installed in current master this messes up Part module and crashes it if switched to part. Should be removed or handled somehow.
_**+
yes, the move was parallel to my integration
I remove it 
but I will write a intro how to generate buttons which to functions in workbenches.
*_*-

PCB does not install: references to fixed folder source:/home/thomas/tmp/PCB!

_**+
this is still open - the file is a 7z file, I have to debug it
ist not running for me too. 
*_*-

Symbollib
Does not look ready for auto install and configure
Looks like it installs fine, but fails on run with:
fn="/usr/lib/freecad/Mod/plugins/FreeCAD-symbols/SymbolsLibrary.FCMacro";exec open(fn).read()
File "", line 140, in
--> File "", line 92, in init
--> NameError: global name 'QtSvg' is not defined
_**+
I will fix it in the SymbolLibrary package
*_*-

Animation does not install properly. Downloaded, extracted but not installed.

PartLibrary Does not look ready for auto install and configure
_**+
yes there must be done a configure patch like in Symbollib
I have to communicate it to yorik.
*_*-

CircularText Macro points to PartLibrary when run
fn="/usr/lib/freecad/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()

Perfect function.
Cura Engine Perfect install, Perfect run
ObjTree Perfect install, Perfect run
DrawingDim Perfect install, Perfect run
Exploded Animation Perfect install, Perfect run
Bolts Perfect install, Perfect run

TestPM
*****default Method FreeCAD-Dir=/usr/lib/freecad/! HOME-Dir=/home/kjetil/! UserData-Dir=/home/kjetil/.FreeCAD/!
@microelly2
Markdown supported
Edit in fullscreen

_**+
I need the next two days
to fix the problems
*_*-

**Comment by kkoksvik** [comment]
Love your work, keep it up :-)

**Comment by kkoksvik** [comment]
When I try to install an already installed plugin. The operation hangs with the last output in python console "backup". no error messages.
It seams to me that the Install just exits, nothing seams to hang. I can immediately try another plugin and the same thing happens.

**Comment by microelly2** [comment]
I have tested today on windows and have done some modifications for the installation process.
I hope the best and will continue  next week.

**Comment by kkoksvik** [comment]
I am trying to solve in Freecad or Arch. I think best to solve underlying problem.
