### ISSUE TITLE
What is 'status.py'

### ISSUE THREAD

**Issue by ManticoreII** [microelly2/freecad-pluginloader#16]
'status.py' is referenced in 'myconfig.yaml' (in both Master & LocalDirs versions) yet appears nowhere else. Is this intended for some future expansion or is it something left from an earlier version that can be safely removed? 
(Really, I just want to know the purpose of the enigmatic 'Sun & 'Mars' icons.)

**Comment by microelly2** [comment]
sun and mars are two icons which got the names  by its colors. I use them for the time I still have no suitable icon for a new feature/macro.
status.py was a placeholder to test these icons.
