### ISSUE TITLE
Symbols library refering to yorik's home folder

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#2]
fn="/usr/share/freecad/Mod/plugins/FreeCAD-symbols/SymbolsLibrary.FCMacro";exec open(fn).read()!
Symbols library path /home/yorik/Sources/FreeCAD-symbolsnot found.
Please set the correct path to your symbols library in the macro script
done

**Comment by microelly2** [comment]
You can set your individual path in FreeCAD Parameters. Inside the SymbolsLibrary Macro your destination is used:

LIBRARYPATH = "/home/yorik/Sources/FreeCAD-symbols"

s=FreeCAD.ParamGet('User parameter:Plugins/symbollib').GetString('destination')
if s<>'':
    LIBRARYPATH = s
else:
    pass

Of course, I should/will  automate this setting.

**Comment by microelly2** [comment]
For every entry configuration info is written to the user Parameters.
