### ISSUE TITLE
Reduce space reqirements

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#3]
Would you consider swapping the top menu-line to a vertical orientation.
![plugin mangager](https://cloud.githubusercontent.com/assets/1898400/7605019/0268c446-f94b-11e4-95c0-0c5037c44fbf.png)

**Comment by microelly2** [comment]
Yes, we can
I still dont know how, but I will find it out and make the direction configurable.

**Comment by microelly2** [comment]
hard coded to west.
