### ISSUE TITLE
2 changes to get started in Archlinux

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#5]
I guess i could make pull request but I want your take on it.

Pluginloader starts and runs seemingly well on arch after these two changes. with one exception. Some plugins installed with it does not run. Will add specific issues for each problem I encounter

in pluginloader.py 

def pathMacro(s):
    '''
    replace shortname by os path
    '''
    for k in ["UserHomePath","UserAppData","AppHomePath"]:
        pat=r"(._)"+k+"/"+"(._)"
        m = re.match(pat, s)
        if m:
            # m.group(0)       # The entire match
            pre=m.group(1)
            post=m.group(2)       # The first parenthesized subgroup.
            inn=FreeCAD.ConfigGet(k)
            if k == "AppHomePath":      #Force sensible Plugin folder
                                if inn == "/usr/":
                                        inn=inn+"share/freecad/"
                                if inn == "/usr/bin/":
                                        inn="/usr/share/freecad/"
            if k == "UserHomePath":
                s2=pre+inn+"/"+post
            else:
                s2=pre+inn+post
            s=s2
    return s
line 136
# fn=0  Commented this line. Had the feeling it was overwriting config.

**Comment by microelly2** [comment]
I would feel me better if I know that I'm on a archlinux machine
when I do this substitution
How do I know from inside python that I'm on a archlinux machine?
can you give me the command to detect the system something like ?

if os.something() =='archlinux':

what is the output of os.uname() on your machines?

**Comment by kkoksvik** [comment]
I am quite sure that there is a bug in FreeCAD when it reports that the AppHomeDir is /usr/. 
My FreeCAD binary file is in /usr/bin. Even if freecad reported that AppHomeDir was in /usr/bin I would not be happy with any software package making /usr/bin/Mod folder on my system. It is bad form and not the way to do it in linux acording to https://wiki.debian.org/FilesystemHierarchyStandard.
If the Mod folder is to be anywhere under /usr/ there are two alternatives /usr/share/freecad/Mod or /usr/local/freecad/Mod(not quit esure here) where the /usr/local probably is the most correct place to put it, since it is installed by an administrator outside of a packagemanager. However since both debian, ubuntu and arch package has already a Mod folder under /usr/share/freecad it seams unnecessary to spread files more. When this glorious Pluginmanager ships standard with FreeCAD and is part of the packaged version the most correct place would be /usr/share/freecad. 

My output is:

> > > os.uname()
> > > ('Linux', 'Arch', '4.0.1-1-ARCH', '#1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015', 'x86_64')
> > > Using this information to check could make it necessary to check for all different linux distributions. I think better to fix Freecad's AppHomePath.

What does AppHomePath report in ubuntu?

**Comment by kkoksvik** [comment]
Looking closer at ubuntu deb files, I see that other applications that use plugins sometimes stores plugins in /usr/lib/gimp/. Have not found any applications that install executable files in /usr/lib/bin like freecad does.

**Comment by microelly2** [comment]
okay, i will report the problem to the freecad forum
the workaround will be to check os.uname until we know why freecad  works so unexpected.

**Comment by microelly2** [comment]
please check the workaround

**Comment by microelly2** [comment]
please check the workaround
