### ISSUE TITLE
Problem activating Assembly2Workbench

### ISSUE THREAD

**Issue by kkoksvik** [microelly2/freecad-pluginloader#6]
!FreeCADGui.activateWorkbench("Assembly2Workbench")!
FreeCADGui.activateWorkbench("Assembly2Workbench")
Traceback (most recent call last):
-->    File "<string>", line 73, in run
-->    File "<string>", line 1, in <module>
-->  KeyError: "No such workbench 'Assembly2Workbench'"
pluginloader started ...
super
pluginloader started ...
['loadtest', 'bolts', 'assembly animation dropbox', 'screw maker', 'sipoc', 'pcb', 'partlib', 'menutest2', 'assembly animation', 'FreeCAD-makros', 'assembly2', 'workfeature', 'curaengin', 'animation', 'defaulttest', 'circular text', 'symbollib', 'drawing dimensioning']
<pluginloader.MyWidget object at 0x7f960909d7a0>
widget shown
super ende
widget shown
assembly2
{'status': 'noignore', 'name': 'assembly2', 'author': 'hamish2914', 'menu': 'Assembly2 Workbench', 'description': 'Assembly Workbench in python', 'exec': 'FreeCADGui.activateWorkbench("Assembly2Workbench")', 'destdir': '/home/kjetil/.FreeCAD/Mod/assembly2', 'source': 'https://github.com/hamish2014/FreeCAD_assembly2/archive/master.zip', 'timestime': 'https://github.com/microelly2/plugin_defaults/timestamp', 'format': 'zipdir', 'icon': '/usr/share/freecad/Mod/plugins/icons/assembly2.png', 'backup': '/home/kjetil/.FreeCAD/Mod/assembly2', 'method': 'zip', 'sourcedir': 'FreeCAD_assembly2-master'}
install or update assembly2
no local version info available
/home/kjetil/tmp/release
no web version info available
Local Version: 99999999999999999999999
Web Version  : 
Need Update 3
/home/kjetil/tmp/yyya
True
zipfile: /home/kjetil/tmp/yyya.zip
https://github.com/hamish2014/FreeCAD_assembly2/archive/master.zip
vor download
targetfile:/home/kjetil/tmp/yyya.zip
extrakts
/home/kjetil/tmp/yyya/FreeCAD_assembly2-master
/home/kjetil/.FreeCAD/Mod/assembly2
backup
move
destination:/home/kjetil/.FreeCAD/Mod/assembly2!
source:/home/kjetil/tmp/yyya/FreeCAD_assembly2-master!
done install
run done
!FreeCADGui.activateWorkbench("Assembly2Workbench")!
FreeCADGui.activateWorkbench("Assembly2Workbench")
Traceback (most recent call last):
-->    File "<string>", line 73, in run
-->    File "<string>", line 1, in <module>
-->  KeyError: "No such workbench 'Assembly2Workbench'"

**Comment by kkoksvik** [comment]
OK, Trigger happy as usual.

Assembly2Workbench starts fine after FreeCAD restart.

**Comment by microelly2** [comment]
After installing/updating a workbench a restart is necessary. I will add a dialog to initiate restart and to gray out not installed workbenches.

**Comment by kkoksvik** [comment]
Nice
